from reportlab.pdfgen import canvas
from reportlab.lib.colors import whitesmoke, black
def generer_carte():
    carte= canvas.Canvas("essai_carte.pdf",pagesize=(243,153))
    carte.setFillColor(whitesmoke)
    carte.setStrokeColor(black)
    carte.setLineWidth(0.5)
    carte.rect(1,1,241,151, stroke=True,fill=True)
    carte.drawImage("C:\projet\multimedia\logo.jpg",10,108,width=50,height=35, preserveAspectRatio=True )
    carte.drawImage("C:\projet\multimedia\icone_homme.jpg", 150,32,width=80,height=80,preserveAspectRatio=True)
    carte.setFont("Helvetica",9)
    carte.setFillColor(black)
    carte.drawString(120,10,"Fait a kinshasa 12/06/2025")
    carte.setFont("Helvetica-Bold",12)
    carte.setFillColor(black)
    carte.drawString(70,127,"CARTE D'ETUDIANT")
    texte= carte.beginText()
    texte.setTextOrigin(10,96)
    texte.setFont("Helvetica-Bold",10)
    texte.setFillColor(black)
    texte.textLine("Nom : Nzola")
    texte.textLine("Post-nom : Samba")
    texte.textLine("Prenom: Joyce")
    texte.textLine("Matricule : SI013724")
    texte.textLine("Promotion : L1 LMD FASI")
    texte.textLine("Adresse : Bandal,5168")
    carte.drawText(texte)
    carte.save()