from base_donnees.etudiant import etudiants
from reportlab.pdfgen import canvas
from reportlab.lib.colors import black,oldlace, seashell, aliceblue, ghostwhite,lightblue,whitesmoke
carte = canvas.Canvas(f"Carte_{etudiants.nom}.pdf", pagesize=(253,143))
carte.setFillColor(whitesmoke)
carte.setLineWidth(1)
carte.setStrokeColor(black)
carte.rect(1,1,width=251,height=141,fill= True, stroke=True)
carte.drawImage("C:\projet\multimedia\logo.jpg",x=5,y=110.5, width=40,height=30)
carte.setFillColor(black)
carte.setFont("Helvetica-Bold",9)
carte.drawString(55,122,"UNIVERISTE PROTESTANTE AU CONGO")
carte.setFillColor(oldlace)
carte.setLineWidth(1)
carte.rect(1,1,width=251,height=108,fill=True,stroke=True)
texte= carte.beginText()
texte.setFillColor(black)
texte.setTextOrigin(x=110,y=85)
texte.setFont("Helvetica-Bold",9)
texte.textLine(f"{etudiants.nom.title()} {etudiants.postnom.title()}")
texte.textLine(f"Prenom: {etudiants.prenom.title()}")
texte.setFont("Helvetica", 9)
texte.textLine(f"Sexe: {etudiants.sexe.upper()}")
texte.textLine(f"Matricule:{etudiants.matricule.upper()}")
texte.textLine(f"Promotion: {etudiants.promotion.upper()}")
texte.textLine(f"Date de naissance: {etudiants.date_naissance}")
carte.drawText(texte)
carte.drawImage(etudiants.photo_path,x=15,y=25, width=75, height=70)
carte.setFont("Helvetica-BoldOblique",9)
carte.drawString(5,10, "CARTE D'ETUDIANT")
carte.save()